source 'https://rubygems.org'

gem 'rails', '3.2.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '1.3.7'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-ui-rails', '4.0.4'
  gem "twitter-bootstrap-rails", '2.2.7'
end

gem 'jquery-rails', '3.0.4'
gem 'jquery-validation-rails', '1.11.1'

gem 'activemodel', '3.2.9'

gem 'rest-client', '1.6.7'

gem 'active_cmis', '0.3.2'

gem "i18n-js", '2.1.2'

gem "therubyracer", '0.11.4'
gem "less-rails", '2.3.3'

gem 'nokogiri', '1.6.0'

gem 'rufus-scheduler', '2.0.23'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
