package jp.aegif.nemaki.rest;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import java.io.InputStream;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.TimeZone;

/**
 * REST endpoint for build information.
 * Provides version and build timestamp for deployment verification.
 *
 * Endpoints:
 * - GET /rest/all/build-info - Returns JSON with core version and build timestamp
 */
@Path("/all/build-info")
public class BuildInfoResource {

    private static final String VERSION = "3.0.0";

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getBuildInfo() {
        try {
            // Get build timestamp from class file modification time
            String buildTimestamp = getBuildTimestamp();

            // Get git commit hash if available
            String gitCommit = getGitCommit();

            StringBuilder json = new StringBuilder();
            json.append("{");
            json.append("\"core\":{");
            json.append("\"version\":\"").append(VERSION).append("\",");
            json.append("\"buildTime\":\"").append(buildTimestamp).append("\"");
            if (gitCommit != null && !gitCommit.isEmpty()) {
                json.append(",\"gitCommit\":\"").append(gitCommit).append("\"");
            }
            json.append("}");
            json.append("}");

            return Response.ok(json.toString()).build();

        } catch (Exception e) {
            return Response.status(500)
                .entity("{\"error\":\"Failed to get build info: " + e.getMessage() + "\"}")
                .build();
        }
    }

    /**
     * Get build timestamp from the class file's last modification time.
     * This reflects when the WAR was built.
     */
    private String getBuildTimestamp() {
        try {
            // Get the class file URL
            URL classUrl = getClass().getResource(getClass().getSimpleName() + ".class");
            if (classUrl != null) {
                long lastModified = classUrl.openConnection().getLastModified();
                if (lastModified > 0) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    sdf.setTimeZone(TimeZone.getTimeZone("Asia/Tokyo"));
                    return sdf.format(new Date(lastModified));
                }
            }
        } catch (Exception e) {
            // Fall through to default
        }

        // Fallback: use current time (indicates runtime, not build time)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        sdf.setTimeZone(TimeZone.getTimeZone("Asia/Tokyo"));
        return sdf.format(new Date()) + " (runtime)";
    }

    /**
     * Try to get git commit hash from build properties if available.
     */
    private String getGitCommit() {
        try {
            // Try to read from git.properties if generated by maven plugin
            InputStream is = getClass().getClassLoader().getResourceAsStream("git.properties");
            if (is != null) {
                Properties props = new Properties();
                props.load(is);
                is.close();
                String commit = props.getProperty("git.commit.id.abbrev");
                if (commit == null) {
                    commit = props.getProperty("git.commit.id");
                }
                if (commit != null && commit.length() > 7) {
                    commit = commit.substring(0, 7);
                }
                return commit;
            }
        } catch (Exception e) {
            // git.properties not available
        }
        return null;
    }
}
