FROM ubuntu:20.04
LABEL maintainer="vadim@clusterside.com"

ARG VERSION=2.3.0
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV MAVEN_OPTS="-Xms2g -Xmx2g"
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
ENV PYTHON="/usr/bin/python3"

RUN mkdir -p /tmp/atlas-src \
    && mkdir -p /apache-atlas \
    && mkdir -p /gremlin

COPY pom.xml.patch /tmp/atlas-src/
COPY settings-arm64.xml /tmp/settings-arm64.xml

RUN --mount=type=cache,target=/root/.m2,id=atlas-m2 apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install apt-utils \
    && apt-get -y install \
        maven \
        wget \
        python \
        python3 \
        build-essential \
        openjdk-8-jdk-headless \
        patch \
        unzip \
    && cd /tmp \
    && wget https://dlcdn.apache.org/atlas/${VERSION}/apache-atlas-${VERSION}-sources.tar.gz \
    && tar --strip 1 -xzvf apache-atlas-${VERSION}-sources.tar.gz -C /tmp/atlas-src \
    && rm apache-atlas-${VERSION}-sources.tar.gz \
    && cd /tmp/atlas-src \
    && sed -i 's/http:\/\/repo1.maven.org\/maven2/https:\/\/repo1.maven.org\/maven2/g' pom.xml \
    && patch -b -f < pom.xml.patch \
    && sed -i '/atlas-falcon-hook-package.xml/d;/atlas-hbase-hook-package.xml/d;/atlas-hive-hook-package.xml/d;/atlas-impala-hook-package.xml/d;/atlas-kafka-hook-package.xml/d;/atlas-sqoop-hook-package.xml/d;/atlas-storm-hook-package.xml/d' distro/pom.xml \
    && mvn clean \
        -s /tmp/settings-arm64.xml \
        -Dmaven.repo.local=/root/.m2/repository \
        -Dhttps.protocols=TLSv1.2 \
        -Dmaven.wagon.http.retryHandler.count=5 \
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
        -Dmaven.wagon.http.ssl.insecure=true \
        -Dmaven.wagon.http.ssl.allowall=true \
        -Dmaven.wagon.http.ssl.ignore.validity.dates=true \
        -DskipTests \
        -Drat.skip=true \
        -pl '!addons/hive-bridge,!addons/hive-bridge-shim,!addons/falcon-bridge,!addons/falcon-bridge-shim,!addons/sqoop-bridge,!addons/sqoop-bridge-shim,!addons/storm-bridge,!addons/storm-bridge-shim,!addons/hbase-bridge,!addons/hbase-bridge-shim,!addons/kafka-bridge,!addons/impala-bridge,!addons/impala-bridge-shim,!addons/impala-hook-api' \
        package -Pdist,embedded-hbase-solr \
    && tar --strip 1 -xzvf /tmp/atlas-src/distro/target/apache-atlas-${VERSION}-server.tar.gz -C /apache-atlas \
    && rm -Rf /tmp/atlas-src \
    && rm -Rf /root/.npm \
    && apt-get -y --purge remove \
        maven \
        unzip \
    && apt-get -y autoremove \
    && apt-get -y clean

COPY conf/hbase/hbase-site.xml.template /apache-atlas/conf/hbase/hbase-site.xml.template
COPY atlas_start.py.patch atlas_config.py.patch /apache-atlas/bin/
COPY conf/atlas-env.sh /apache-atlas/conf/atlas-env.sh
COPY conf/gremlin /gremlin/

WORKDIR /apache-atlas/bin
RUN patch -b -f < atlas_start.py.patch \
    && patch -b -f < atlas_config.py.patch

WORKDIR /apache-atlas/conf
RUN sed -i 's/\${atlas.log.dir}/\/apache-atlas\/logs/g' atlas-log4j.xml \
    && sed -i 's/\${atlas.log.file}/application.log/g' atlas-log4j.xml

WORKDIR /apache-atlas/bin
RUN ./atlas_start.py -setup || true
RUN ./atlas_start.py & \
    touch /apache-atlas/logs/application.log \
    && tail -f /apache-atlas/logs/application.log | sed '/Defaulting to local host name/ q' \
    && sleep 10 \
    && ./atlas_stop.py \
    && truncate -s0 /apache-atlas/logs/application.log

CMD ["/bin/bash", "-c", "/apache-atlas/bin/atlas_start.py; tail -fF /apache-atlas/logs/application.log"]
