/**
 * API Documentation Component using Swagger UI
 *
 * Displays the OpenAPI 3.0 specification for NemakiWare CMIS REST API.
 * Only accessible to admin users via the admin menu.
 *
 * Authentication: Uses requestInterceptor to add AUTH_TOKEN header
 * for fetching the OpenAPI spec and making API calls.
 */

import React, { useCallback } from 'react';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import { Card, Typography, Space, Alert } from 'antd';
import { ApiOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { AuthService } from '../../services/auth';

const { Title, Text } = Typography;

interface ApiDocsProps {
  repositoryId: string;
}

export const ApiDocs: React.FC<ApiDocsProps> = ({ repositoryId }) => {
  const { t } = useTranslation();

  // OpenAPI spec URL - generated by swagger-jaxrs2-jakarta
  const openApiUrl = '/core/api/v1/cmis/openapi.json';

  // Request interceptor: merge the app's standard headers into every Try-it-out request.
  // getAuthHeaders() carries X-Requested-With (the CSRF bypass header) — the previous version
  // only copied AUTH_TOKEN, which is never set in cookie-based auth, so state-changing
  // operations executed from Swagger UI would have been rejected by the CSRF filter (3.3.1 #8).
  const requestInterceptor = useCallback((req: Record<string, unknown>) => {
    const authService = AuthService.getInstance();
    req.headers = {
      ...((req.headers as Record<string, string>) || {}),
      ...authService.getAuthHeaders()
    };
    // Auth is an HttpOnly cookie. swagger-client's fetch omits credentials by default, so
    // every executed request was a 401; the SwaggerUI `withCredentials` prop is not part of
    // swagger-ui-react's typed surface, so the reliable place to say it is the request itself.
    req.credentials = 'same-origin';
    return req;
  }, []);

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <Space direction="vertical" size="middle" style={{ width: '100%', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <ApiOutlined style={{ fontSize: 24, color: '#1890ff' }} />
          <Title level={3} style={{ margin: 0 }}>{t('apiDocs.title')}</Title>
        </div>
        <Text type="secondary">{t('apiDocs.description')}</Text>
        <Alert
          message={t('apiDocs.note')}
          description={t('apiDocs.noteDescription', { repositoryId })}
          type="info"
          showIcon
        />
      </Space>

      <Card
        style={{ flex: 1, overflow: 'auto' }}
        styles={{ body: { padding: 0 } }}
      >
        <SwaggerUI
          url={openApiUrl}
          docExpansion="list"
          defaultModelsExpandDepth={1}
          displayRequestDuration={true}
          filter={true}
          showExtensions={true}
          showCommonExtensions={true}
          requestInterceptor={requestInterceptor}
        />
      </Card>
    </div>
  );
};

export default ApiDocs;
