/**
 * API Documentation Component using Swagger UI
 *
 * Displays the OpenAPI 3.0 specification for NemakiWare CMIS REST API.
 * Only accessible to admin users via the admin menu.
 *
 * Authentication: Uses requestInterceptor to add AUTH_TOKEN header
 * for fetching the OpenAPI spec and making API calls.
 */

import React, { useCallback } from 'react';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import { Card, Typography, Space, Alert } from 'antd';
import { ApiOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { AuthService } from '../../services/auth';

const { Title, Text } = Typography;

interface ApiDocsProps {
  repositoryId: string;
}

export const ApiDocs: React.FC<ApiDocsProps> = ({ repositoryId }) => {
  const { t } = useTranslation();

  // OpenAPI spec URL - generated by swagger-jaxrs2-jakarta
  const openApiUrl = '/core/api/v1/cmis/openapi.json';

  // Request interceptor to add authentication headers
  const requestInterceptor = useCallback((req: Record<string, unknown>) => {
    const authService = AuthService.getInstance();
    const headers = authService.getAuthHeaders();

    // Add auth headers to the request
    if (headers.AUTH_TOKEN) {
      req.headers = {
        ...(req.headers as Record<string, string> || {}),
        AUTH_TOKEN: headers.AUTH_TOKEN
      };
    }
    return req;
  }, []);

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <Space direction="vertical" size="middle" style={{ width: '100%', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <ApiOutlined style={{ fontSize: 24, color: '#1890ff' }} />
          <Title level={3} style={{ margin: 0 }}>{t('apiDocs.title')}</Title>
        </div>
        <Text type="secondary">{t('apiDocs.description')}</Text>
        <Alert
          message={t('apiDocs.note')}
          description={t('apiDocs.noteDescription', { repositoryId })}
          type="info"
          showIcon
        />
      </Space>

      <Card
        style={{ flex: 1, overflow: 'auto' }}
        styles={{ body: { padding: 0 } }}
      >
        <SwaggerUI
          url={openApiUrl}
          docExpansion="list"
          defaultModelsExpandDepth={1}
          displayRequestDuration={true}
          filter={true}
          showExtensions={true}
          showCommonExtensions={true}
          requestInterceptor={requestInterceptor}
        />
      </Card>
    </div>
  );
};

export default ApiDocs;
