FROM aegif/nemakibuild

# COPY ../../../../ /app_setup

# RUN cd /app_setup/action && mvn install
# RUN cd /app_setup/common && mvn install

ADD ./dep/core.tar.gz /dep/
ADD ./dep/action.tar.gz /dep/